### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by bahamat** [mitchellh/cli#18]
````
$ go version
go version go1.4.2 solaris/amd64
$ go build github.com/mitchellh/cli 
# github.com/mitchellh/cli
src/github.com/mitchellh/cli/ui.go:79: undefined: terminal.IsTerminal
src/github.com/mitchellh/cli/ui.go:81: undefined: terminal.ReadPassword
````

**Comment by bahamat** [comment]
Is there any other information I can provide that can help?

**Comment by fatih** [comment]
This is invalid. Cli can be built successfully. Travis shows it ok too: https://travis-ci.org/mitchellh/cli

**Comment by mitchellh** [comment]
I think it probably doesn't build on solaris. If you submit a PR to fix this I'd be happy to help, but it isn't an OS I'm interested in.

**Comment by bahamat** [comment]
Even though you don't care, can we at least hold this issue open for other people encountering this problem so they can know that it is a known issue? Leaving it open may also attract someone who can fix it.
