### ISSUE TITLE
Add "subcommand chooser"

### ISSUE THREAD

**Issue by yegle** [mitchellh/cli#19]
The `cli.CLI` struct should add a `SubcommandChooser`, which is a `func` that return a `cli.Command`.

The reason would be when the specified subcommand doesn't exist  (see also pull reqeust https://github.com/mitchellh/cli/pull/10) the behaviour can be controlled by the user.

Also I can implement something similar to `busybox`'s behaviour that by creating a link `foo` to my binary, I can invoke the `foo` subcommand directly.

If this idea looks good to you I can send a PR and implement it.

**Comment by mitchellh** [comment]
This looks good! If you submit a PR I'd be happy to merge this. Going to close this issue though since I don't plan on doing this myself in the short term. Thanks!

**Comment by yegle** [comment]
FYI this is implemented in https://github.com/mitchellh/cli/pull/20
