### ISSUE TITLE
Sporadic test failures in "TestCLIRun_printCommandHelpSubcommands"

### ISSUE THREAD

**Issue by onlyjob** [mitchellh/cli#30]
With Golang 1.6 _TestCLIRun_printCommandHelpSubcommands_ sometimes fail as follows:

```
--- FAIL: TestCLIRun_printCommandHelpSubcommands (0.00s) 
        cli_test.go:344: bad: []string{"-h", "foo"} 

                '"donuts\n\nSubcommands:\n\n    longer    hi!\n    bar       hi!\n\n"' 

                '"donuts\n\nSubcommands:\n\n    bar       hi!\n    longer    hi!\n\n"' 
```

**Comment by marco-m** [comment]
@onlyjob are the sporadic test failures reproductible with the current go or can this ticket be closed?

**Comment by onlyjob** [comment]
There is nothing I know to justify closure of this ticket but I did not test in a long time...

**Comment by sarkis** [comment]
I am unable to reproduce this on:

```
❯ go version
go version go1.13 darwin/amd64
```

I tried to run the following multiple times with no reproduction of failure: `go test -count 1000 .`

**Comment by onlyjob** [comment]
Fair enough, thanks for trying.

**Comment by mitchellh** [comment]
This looks fixed.
