### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [mitchellh/cli#31]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for cli and versioning would help Debian keep up with development.

**Comment by mnzt** [comment]
+1

With the support added into many vendoring tools, this practice should start becoming a standard. Can we get your thoughts @mitchellh?

**Comment by libeclipse** [comment]
Agreed. The lack of a version number is a big problem when `cli` is used in conjunction with other tools. In its current state, it's disruptive to the workflow.

**Comment by aviau** [comment]
Any news on this?

**Comment by doertedev** [comment]
At least a bit of feedback would really be appreciated.

**Comment by onlyjob** [comment]
A year passed and still no tags?

Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by sergiughf** [comment]
Any updates on this?

**Comment by rostislav-rocket** [comment]
+1 please consider using tags

**Comment by mitchellh** [comment]
Done!

**Comment by onlyjob** [comment]
Thanks. :)
