### ISSUE TITLE
Top level help shows all subcommand children

### ISSUE THREAD

**Issue by dadgar** [mitchellh/cli#32]
See the `fs` commands in the attached picture This is a regression in behavior.

![help](https://cloud.githubusercontent.com/assets/1047914/13907101/e9b44886-eea3-11e5-8203-0d3faaee3832.png)

**Comment by mitchellh** [comment]
I looked into this before and the bug exists in Nomad here: https://github.com/hashicorp/nomad/blob/master/main.go#L32

You need to also exclude the subcommands.

**Comment by dadgar** [comment]
Thanks. The behavior did change. I wonder if hiding should be an option for the library to do automatically
