### ISSUE TITLE
Compatibility with standard library `flag` package

### ISSUE THREAD

**Issue by evillemez** [mitchellh/cli#48]
I feel like I've missed something obvious - but not finding the answer anywhere in documentation or code.  Or, if I did, I didn't understand it.

Is this library incompatible with the standard library `flag` package?

I've defined some flags, but they don't seem to get parsed when a command is specified.  It doesn't matter if the flags are specified before or after the command.  I have a program that's expecting reference to a config file via a flag, the program just exits early if one isn't specified.  For example:

```
$ program --conf conf.yml  #executes, but just prints out list of available commands, as none was specified
$ program --conf conf.yml status  # executes, but doesn't call the `status` command, just prints list of available commands
$ program status --conf conf.yml  #immediately exits because it didn't get the `conf` flag
```

**Comment by mitchellh** [comment]
It is. This CLI library actually doesn't parse flags at all (except "-h/--help" and "-v/--version"). This allows the consumer to use whatever flag parsing library they want. This library just passes it to you as `[]string`

**Comment by evillemez** [comment]
Ok, thanks, my issue must be in specifically how I'm using `flag`.

**Comment by evillemez** [comment]
If anyone else has some initial confusion on this point:  The problem was in not setting `cli.Args` properly after parsing the flags.  I was still using `os.Args[1:]`, not `flag.Args()`:

Assuming the command was `$ program --conf conf.yml status`

```
func main() {
    // ... set up flags, call flag.Parse()
    c := cli.NewCLI("app", "1.0.0")
    c.Args = flag.Args()  //previously was `os.Args[1:]`
    c.Commands = map[string]cli.CommandFactory{
        "status": statusCommandFactory,
    }
// ...
}
```

I appreciate the response earlier, and apologize for the noise.
