### ISSUE TITLE
Nested Subcommand Help

### ISSUE THREAD

**Issue by dadgar** [mitchellh/cli#53]
The generated subcommands should only show immediate child when listing subcommands:

```
nomad operator
Usage: nomad operator <subcommand> [options]

  Provides cluster-level tools for Nomad operators, such as interacting with
  the Raft subsystem. NOTE: Use this command with extreme caution, as improper
  use could lead to a Nomad outage and even loss of data.

  Run nomad operator <subcommand> with no arguments for help on that subcommand.

Subcommands:

    raft                Provides access to the Raft subsystem
    raft list-peers     List peers from the Raft quorum
    raft remove-peer    Remove peers from the Raft quorum
```

Expected behavior would be to just show `raft`

**Comment by dadgar** [comment]
@mitchellh Ping. Getting closer to 0.5.5 final and don't want to release with this

**Comment by mitchellh** [comment]
Hey @dadgar,  I added a test for this and can't reproduce it: https://github.com/mitchellh/cli/commit/8d6d9ab3c912dcb005ece87c40a41b9e73e1999a

Are you using this differently?

**Comment by dadgar** [comment]
Updated the vendored version and problem went away! So must have got fixed at some point 👍
