### ISSUE TITLE
panic if a subcommand is wrapped in double quotes and contains spaces

### ISSUE THREAD

**Issue by minamijoyo** [mitchellh/cli#68]
This issue was originally reported as https://github.com/hashicorp/terraform/issues/16642, debugging for a while, it turns out to be a bug of `mitchellh/cli`.

Panic will occur under the following conditions:

- A `CLI.commandNested` is `true`
- The subcommand is wrapped in double quotes and contains spaces ( `./app "foo bar"` )
- If there is no double quote, it is a valid subcommand ( `./app foo bar` )

Minimum reproduction code as follows:

```main.go
package main

import (
	"log"
	"os"

	"github.com/mitchellh/cli"
)

type FooBar struct{}

func (f *FooBar) Help() string {
	return "app foo bar"
}

func (f *FooBar) Run(args []string) int {
	log.Println("Foo Bar!")
	return 0
}

func (f *FooBar) Synopsis() string {
	return "Print \"Foo Bar!\""
}

func main() {
	c := cli.NewCLI("app", "1.0.0")
	c.Args = os.Args[1:]
	c.Commands = map[string]cli.CommandFactory{
		"foo bar": func() (cli.Command, error) {
			return &FooBar{}, nil
		},
	}

	exitStatus, err := c.Run()
	if err != nil {
		log.Println(err)
	}

	os.Exit(exitStatus)
}
```

```
$ go run main.go foo bar
2017/11/26 22:13:50 Foo Bar!

$ go run main.go "foo bar"
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/mitchellh/cli.(*CLI).processArgs(0xc420090000)
        /Users/m-morita/src/github.com/mitchellh/cli/cli.go:667 +0xb8c
github.com/mitchellh/cli.(*CLI).init(0xc420090000)
        /Users/m-morita/src/github.com/mitchellh/cli/cli.go:382 +0x3b9
github.com/mitchellh/cli.(*CLI).(github.com/mitchellh/cli.init)-fm()
        /Users/m-morita/src/github.com/mitchellh/cli/cli.go:158 +0x2a
sync.(*Once).Do(0xc4200900b8, 0xc42004def8)
        /usr/local/Cellar/go/1.9.1/libexec/src/sync/once.go:44 +0xbe
github.com/mitchellh/cli.(*CLI).Run(0xc420090000, 0xc420074270, 0x11858dc, 0x7)
        /Users/m-morita/src/github.com/mitchellh/cli/cli.go:171 +0x6d
main.main()
        /Users/m-morita/work/tmp/20171124/main.go:34 +0x13f
```

Panic occurs in the following lines.

https://github.com/mitchellh/cli/blob/65fcae5817c8600da98ada9d7edf26dd1a84837b/cli.go#L667

If wrapping in double quotes then `len(c.Args) = 1` , but the args matches `c.commandTree.LongestPrefix (searchKey)`, so the index `i` is added by the number of spaces, resulting in out-of-range access.

I think this is an edge case, but it is not good to panic by user input.
How should we fix it?

**Comment by mitchellh** [comment]
Hah! This is rather strange...

Technically the double quotes are supposed to signify that that is _one_ argument. So I propose we treat it as such, so `cli "foo bar"` **!=** `cli foo bar`. When scripting, its easy enough to drop a subcommand with `cli $command_with_spaces` or `cli ${ARRAY[*]}`, so I don't think this affects scripting at all.

I'll take a look at this and get a fix in.

**Comment by minamijoyo** [comment]
@mitchellh Thanks!
